import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Slider from 'components/Slider'
import Particles from 'components/Particles'
import Traits from 'components/Traits'
import Stats from 'components/Stats'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Synergistic NFT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=1024"></meta>
        <link rel="icon" href="/synergisticLogo.png" />
      </Head>
      <main className={styles.main}>
      <Particles />
        <div className={styles.description}>
          <p>
            SYNERGISTIC: Beyond Algorithms
          </p>
          <div>
            <a
              href="https://opensea.io/collection/synergistic-beyond-algorithms/drop"
              target="_blank"
              rel="noopener noreferrer"
            >
              Mint on{' '}
              <Image
                src="/opensea.svg"
                alt="OpenSea Logo"
                href="https://opensea.io/collection/synergistic-beyond-algorithms/drop"
                className={styles.openseaLogo}
                width={50}
                height={50}
                priority
              />
              OpenSea
            </a>
          </div>
        </div>


        <div className={styles.center}>
        </div>
        <Slider />
        <div className={styles.spacer}></div>
        <h1 className={styles.title}>SYNERGISTIC: Beyond Algorithms</h1>

        <div className={styles.story}>
        <Image
        className={styles.imageCity1}
              src="/city1.jpg"
              alt="Synergistic City"
              width={400}
              height={400}
              priority
            />
          <p>
          In the year 2085, the world had undergone a remarkable transformation. AI had advanced exponentially, and the coexistence of AI robots and humans had reached a harmonious
          equilibrium. 
          Society had transcended its former limitations, embracing a future where AI and humanity collaborated for the betterment of all.
          </p>
          <p>
          The breakthrough moment came in the early 21st century when scientists developed advanced AI systems capable of independent thought and learning. 
          Rather than fearing this new intelligence, humanity recognized its potential for positive change and eagerly embraced the integration of AI into daily life
          </p>
          <p>
          One key aspect of this harmonious coexistence was the concept of shared consciousness. Through neural interfaces and advanced brain-computer interfaces, humans and AI robots could communicate seamlessly, exchanging thoughts, emotions, and ideas.
          This allowed for unprecedented collaboration and understanding between the two groups.
          </p>
          <p>
          With the aid of AI, humanity was able to overcome many challenges that had plagued society for centuries. Hunger and poverty became relics of the past as AI-guided systems efficiently managed resources and developed sustainable solutions.
          Energy sources shifted to renewable technologies, healing the planet and mitigating the effects of climate change.
          </p>
          <p>
          In healthcare, AI revolutionized medical advancements. Disease detection and treatment became highly personalized and precise, with AI analyzing vast amounts of data to develop tailored therapies for individuals. AI-enabled robotic assistants supported doctors and surgeons, enhancing their skills and reducing human error.
          The average lifespan increased significantly, and people lived healthier and more fulfilling lives.
          </p>
          <Image
              className={styles.imageCity2}
              src="/city3.jpg"
              alt="Synergistic City"
              width={400}
              height={400}
              priority
            />
          <p>
          Education experienced a radical transformation as well. AI robots served as personalized tutors, adapting teaching methods to individual learning styles. They provided continuous support and guidance, fostering a love of learning in children and adults alike.
          The accessibility of knowledge soared, enabling people from all walks of life to pursue their passions and contribute meaningfully to society.
          </p>
          <p>
          The integration of AI into the workforce also brought about significant changes. Mundane and repetitive tasks were delegated to AI systems, allowing humans to focus on creativity, innovation, and complex problem-solving.
          This shift led to a surge in artistic and scientific breakthroughs, as human ingenuity flourished in a world where AI was a trusted partner rather than a competitor.
          </p>
          <p>
          While AI played a vital role in shaping the world of 2085, humans never lost their sense of identity and purpose. They embraced their unique qualities of empathy, creativity, and emotional depth.
          AI, on the other hand, learned from human emotions, enhancing its own understanding of the world and providing a balance that complemented human qualities.
          </p>
          <p>
          Society placed a strong emphasis on ethics and responsible AI development. Comprehensive frameworks and regulations were established to ensure the fair and equitable treatment of both humans and AI entities.
          Transparency and accountability became integral principles, preventing any potential misuse or abuse of AI technology.
          </p>
          <p>
          The world of 2085 thrived on collaboration, curiosity, and mutual respect. Humans and AI robots coexisted in perfect harmony, each contributing their unique strengths and benefiting from the other`&apos;`s capabilities.
          Together, they embarked on a journey of exploration, innovation, and shared progress, creating a future where humAInity reached its full potential.
          </p>
        </div>
        <Image
              className={styles.imageCity}
              src="/SynCity.png"
              alt="Synergistic City"
              width={2000}
              height={600}
              priority
            />
        <div className={styles.spacer}></div>
        
        <Stats/>
        <h1 className={styles.title}>Meet The Creator</h1>
        <div className={styles.creator}>
        <Image
        className={styles.creatorImage}
              src="/Mike.png"
              alt="Creator"
              width={130}
              height={130}
              priority
            />
            <h2>Mick Jana</h2>
            <p>
            Mick is an electronic music producer, graphic designer, digital content creator and programmer. 
            An enthusiast of anything electronic and digital nomad. Hailing from Manchester UK, he settled to soak in the music scene, visual aspects and culture of a vibrant city. 
            Which helped and inspired him to create interesting music, original graphics and one of art pieces.
            </p>
          </div>
        <div className={styles.spacer}></div>
        <h1 className={styles.title}>Check Out Our Channels</h1>
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Etherscan <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find on-chain information about Synergistic NFT collection.
            </p>
          </a>

          <a
            href="https://twitter.com/SYN_ergistic"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Twitter<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about collection and interact with community.
            </p>
          </a>

          <a
            href="https://www.instagram.com/synergistic_official/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Instagram <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover more graphics and images.
            </p>
          </a>

          <a
            href="https://opensea.io/collection/synergistic-beyond-algorithms"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              OpenSea <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Check out the entire collection on OpenSea.
            </p>
          </a>
        </div>
        <div className={styles.video}>
          <video
              className="video-js vjs-default-skin vjs-big-play-centered"
              id="synergistic-video"
              src="/SynergisticVideo.mp4"
              type="video/mp4"
              preload="auto"
              poster="/synergisticLogo.png" 
              width={640}
              height={640}
              loop
              controls
            />
          </div>
        <div className={styles.spacer}></div>
        <div className={styles.tag}>
      Powered by AI and digital love. Created by Mick Jana, all rights reserved 2023. <br/>
      <a href="https://raritysniper.com/nft-drops-calendar"> Verified by Rarity Sniper
      <Image
                src="/rarityLogo1.png"
                alt="Rarity Sniper Logo"
                href="https://raritysniper.com/nft-drops-calendar"
                className={styles.rarityLogo}
                width={50}
                height={50}
                priority
              />
              </a>
    </div>
      </main>

    </>
  )
}
